                                                                                                                                                                                                                                                                                                                                                                                                                                                                 f1
#!/bin/bash

#This is a part of automation to get System Report 

#To Get system information
hostname=$(hostname)
uptime=$(uptime -p)
distro=$(source /etc/os-release && echo "$NAME $VERSION_ID")

#This will get hardware information
cpu=$(lscpu | grep "Model name" | awk '{print $3, $4}')
# Get CPU Speed
speed=$(awk '/^cpu MHz/ {printf "%.2f", $4}' /proc/cpuinfo)

# For Maximum CPU Speed
max_speed=$(awk '/^model name/ {print $NF; exit}' /proc/cpuinfo | cut -d "@" -f2 | cut -d "." -f1 | sed 's/GHz//')

# If the maximum speed is in GHz, convert it to MHz
if [[ $max_speed == "GHz" ]]; then
    max_speed=$(echo "$max_speed * 1000" | bc)
fi
ram=$(free -m | awk 'NR==2{printf "%.2f GB", $2/1024}')
disks=$(lsblk -d -o NAME,SIZE,MODEL | sed '1d;s/^/Disk: /')
video=$(lshw -c video | grep "product:" | awk '{print $2}')

# network information will be generated using this
fqdn=$(hostname -f)
host_address=$(ip a | grep "inet " | awk '{print $2}')
gateway_ip=$(ip r | grep "default" | awk '{print $3}')
dns_server=$(cat /etc/resolv.conf | grep "nameserver" | awk '{print $2}')

# network interfaces information  will be generated
IP_ADDRESS=$(ip a | grep "inet " | grep -v "127.0.0.1" | awk '{print $2}')
interfaces=$(ip a | grep "inet " | awk '{print $2, " / ", $3}')

# to generate system status
users_logged_in=$(who | awk '{print $1}' | sort | uniq | paste -s -d, -)
disk_space=$(df -h --local | grep -vE '^Filesystem|tmpfs|cdrom' | awk '{print $6, $4}')
load_averages=$(uptime | awk -F 'load average' '{print $2}')
memory_allocation=$(free -h | awk 'NR==2{print $3, " / ", $7}')
listening_ports=$(ss -tuln | wc -l)
ufw_rules=$(sudo ufw status verbose | wc -l)
load_average=$(cat /proc/loadavg)
process_count=$(ps -e | wc -l)

#Let's Print the report
echo
echo "System Report generated by $USER, $(date +"%Y-%m-%d %H:%M:%S")"
echo
echo "System Information"
echo "------------------"
echo "Hostname: $hostname"
echo "OS: $distro"
echo "Uptime: $uptime"
echo
echo "Hardware Information"
echo "--------------------"
echo "CPU: $cpu"
echo "Speed: $speed MHz (Max: $max_speed MHz)"
echo "Ram: $ram"
echo "Disk(s): $disks"
echo "Video: $video"
echo
echo "Network Information"
echo "-------------------"
echo "FQDN: $fqdn"
echo "Host Address: $host_address"
echo "Gateway IP: $gateway_ip"
echo "DNS Server: $dns_server"
echo "InterfaceName: $interfaces"
echo "IP Address: $IP_ADDRESS"
echo
echo "System Status"
echo "-------------"
echo "Users Logged In: $users_logged_in"
echo "Disk Space:"
echo "$disk_space"
echo "Process Count: $process_count"
echo "Load Averages: $load_average"
echo "Memory Allocation: $memory_allocation"
echo "Listening Network Ports: $listening_ports"
echo "UFW Rules: $ufw_rules"
echo
